# Generated by Django 5.1.7 on 2025-04-09 19:06

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('masp', models.AutoField(primary_key=True, serialize=False)),
                ('tensp', models.CharField(max_length=255)),
                ('mota', models.TextField()),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('soluongtonkho', models.IntegerField()),
                ('hinhanh', models.ImageField(blank=True, null=True, upload_to='sanpham/')),
                ('danhmuc', models.CharField(default='Chưa phân loại', max_length=255)),
                ('ngaytao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sanpham',
                'ordering': ['-ngaytao'],
            },
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('mand', models.AutoField(primary_key=True, serialize=False)),
                ('hoten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sdt', models.CharField(blank=True, max_length=15, null=True)),
                ('loainguoidung', models.CharField(choices=[('KhachHang', 'Khách Hàng'), ('QuanTriVien', 'Quản Trị Viên')], default='KhachHang', max_length=20)),
                ('ngaytao', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'nguoidung',
                'ordering': ['-ngaytao'],
            },
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('madh', models.AutoField(primary_key=True, serialize=False)),
                ('ngaydathang', models.DateTimeField(auto_now_add=True)),
                ('tongtien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trangthai', models.CharField(choices=[('ChoXacNhan', 'Chờ Xác Nhận'), ('DangGiao', 'Đang Giao'), ('HoanThanh', 'Hoàn Thành'), ('DaHuy', 'Đã Hủy')], default='ChoXacNhan', max_length=20)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donhangs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donhang',
                'ordering': ['-ngaydathang'],
            },
        ),
        migrations.CreateModel(
            name='GioHang',
            fields=[
                ('magh', models.AutoField(primary_key=True, serialize=False)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='giohangs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'giohang',
            },
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('madg', models.AutoField(primary_key=True, serialize=False)),
                ('sosao', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('binhluan', models.TextField(blank=True, null=True)),
                ('ngaydanhgia', models.DateTimeField(auto_now_add=True)),
                ('nguoidung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danhgias', to=settings.AUTH_USER_MODEL)),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danhgias', to='api.sanpham')),
            ],
            options={
                'db_table': 'danhgia',
                'ordering': ['-ngaydanhgia'],
            },
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('matt', models.AutoField(primary_key=True, serialize=False)),
                ('sotien', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phuongthucthanhtoan', models.CharField(choices=[('TienMat', 'Tiền Mặt'), ('ChuyenKhoan', 'Chuyển Khoản'), ('TheTinDung', 'Thẻ Tín Dụng')], max_length=20)),
                ('trangthaithanhtoan', models.CharField(choices=[('ChuaThanhToan', 'Chưa Thanh Toán'), ('DaThanhToan', 'Đã Thanh Toán')], default='ChuaThanhToan', max_length=20)),
                ('ngaythanhtoan', models.DateTimeField(blank=True, null=True)),
                ('donhang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thanhtoan', to='api.donhang')),
            ],
            options={
                'db_table': 'thanhtoan',
            },
        ),
        migrations.CreateModel(
            name='ChiTietGioHang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.PositiveIntegerField()),
                ('giohang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet', to='api.giohang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet_giohang', to='api.sanpham')),
            ],
            options={
                'db_table': 'chitietgiohang',
                'unique_together': {('giohang', 'sanpham')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('soluong', models.PositiveIntegerField(default=1)),
                ('gia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donhang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet', to='api.donhang')),
                ('sanpham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chitiet_donhang', to='api.sanpham')),
            ],
            options={
                'db_table': 'chitietdonhang',
                'unique_together': {('donhang', 'sanpham')},
            },
        ),
    ]
